# 使用 Node.js 官方映像作為基礎
FROM node:22-alpine

# 設定工作目錄
WORKDIR /app

# 複製 package.json 和 package-lock.json
COPY package*.json ./

# 安裝依賴
RUN npm install && \
    npm install -g nodemon

# 複製其餘的程式碼
COPY . .

# 暴露端口
EXPOSE 3000

# 啟動開發伺服器
CMD ["npm", "run", "docker:dev"]
